name: AIReaderApp
options:
  bundleIdPrefix: com.aireader
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_PREVIEWS: YES

packages:
  ZipArchive:
    url: https://github.com/ZipArchive/ZipArchive.git
    from: "2.5.0"
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.6.0"

targets:
  AIReaderApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AIReaderApp
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: ZipArchive
      - package: SwiftSoup
    settings:
      base:
        INFOPLIST_FILE: AIReaderApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.aireader.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    info:
      path: AIReaderApp/Info.plist
      properties:
        CFBundleDisplayName: AI Reader
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: true
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: org.idpf.epub-container
            UTTypeDescription: EPUB Document
            UTTypeConformsTo:
              - public.data
              - public.composite-content
            UTTypeTagSpecification:
              public.filename-extension:
                - epub
              public.mime-type:
                - application/epub+zip
        CFBundleDocumentTypes:
          - CFBundleTypeName: EPUB Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Default
            LSItemContentTypes:
              - org.idpf.epub-container
            CFBundleTypeIconFiles: []

schemes:
  AIReaderApp:
    build:
      targets:
        AIReaderApp: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
